# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restroom Review' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Restroom Review
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'


pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Email'

pod 'FirebaseFirestoreSwift', '8.13.0-beta'
pod 'GeoFire/Utils'

pod 'Cosmos', '~> 23.0'
pod 'lottie-ios'
end
