# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restroom Review' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Restroom Review
pod 'Firebase/Core'
pod 'Firebase/Auth'

pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Email'

end
